version: '3.8'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ac2_ac
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: matheusap27/ac2_ca:latest
    networks:
      - default  # Certifique-se de que está usando a rede adequada
    environment:
      DB_HOST: database
    ports:
      - "8686:8080"
volumes:
  db-volume: